

name: Deploy Netlify Site



on:
  push:
    branches: [ master ]
    
  
jobs: 

  build:
  
    runs-on: ubuntu-latest
    

    steps:
    
      - uses: actions/checkout@v2
      
      
      - name: Deploy Site 
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
